### ISSUE TITLE
Активировать передачу номера в retailCRM

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#103]
Что означает данная опция?

**Comment by iyzoer** [comment]
Означает, что если она активирована, в retailCRM будет передан номер заказа из WC.

**Comment by ovdienko** [comment]
Не совсем понятно, так как номер заказа при создании заказа в любом случае передается.

Наверное, корректнее сказать, что при включении этой опции номер заказа будет обновляться при его обновлении в WC.
