### ISSUE TITLE
WC_Retailcrm_Proxy::__call(): Notice: Undefined variable: response

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/woocommerce-module#118]
В методе `__call()` выражение `return $response;` находится вне `try-catch`, из-за чего может возникать `Notice: Undefined variable: response`. Пример такого случая - последствие #117.

**Comment by Neur0toxine** [comment]
Добрый день! Действительно, проблема присутствует. Она будет исправлена в следующем релизе. Также фикс должен исправить ошибки в случае отсутствия доступа к API retailCRM.
