### ISSUE TITLE
Cupon discount don't load to crm.

### ISSUE THREAD

**Issue by OlegApanovich** [retailcrm/woocommerce-module#19]
I try to test it with such coupon settings https://prnt.sc/gpffzv on woocommerce 2.6 and 3.0 version.

**Comment by iyzoer** [comment]
You use the coupon in the order?

**Comment by gwinn** [comment]
Можете приложить скрин заказа в WooCommerce в котором использован данный купон?

**Comment by OlegApanovich** [comment]
Ребята сори но уже пару месяцев прошло и я не помню как смоделировать эту
ошибку. Можете закрыть вопрос.

24 нояб. 2017 г. 2:49 ПП пользователь "Alex Lushpai" <
notifications@github.com> написал:
