### ISSUE TITLE
Как не создавать новый заказ в woocommerce?

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#26]
Подскажите пожалуйста, при создании заказа вручную в ЦРМ, создается так же заказ в Woocommerce, в большинстве случаев эта функция не нужна, так как в Woocomerce нельзя задать номер заказа. То есть номера созданных вручную заказов в retailcrm будут отличаться от выгруженных в woocommerce. Вопрос в следующем, как запретить плагину создавать заказы в магазине woocommerce? комментирую содержимое функции - public function orderCreate($order_id), не помогает.

**Comment by iyzoer** [comment]
Метод orderCreate отвечает за создание заказа в CRM.
Все изменения, которые передаются в магазин обрабатываются в классе WC_Retailcrm_History.
Вы можете создать в wp-content директорию retailcrm-custom и в неё поместить файл class-wc-retailcrm-history.php со своей логкой. За создание заказа в магазине отвечают строки с 291 по 398.
