### ISSUE TITLE
Заказы приходят без учета скидок

### ISSUE THREAD

**Issue by haidarzhy** [retailcrm/woocommerce-module#28]
В RetailCRM все заказы приходят с суммой на основе базовой цены, акционная цена, по которой клиент сделал заказ, игнорируется.

**Comment by iyzoer** [comment]
Рассмотрим возможность передавать цену товара из корзины с учетом скидок.

**Comment by rustykobra** [comment]
Лучше даже, наверное, из заказов. 
Подгрузилась целая база заказов с базовыми ценами, хотя было несколько периодов с разными скидками.

**Comment by iyzoer** [comment]
Модернизировали выгрузку заказов, теперь цена товара подтягивается с учетом его стоимости в заказе.
