### ISSUE TITLE
Конфликт с плагином почты России

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#29]
Помогите пожалуйста разобраться почему не хочет работать вместе с плагином доставки Почты России (https://ru.wordpress.org/plugins/russian-post-and-ems-for-woocommerce/)

Оба плагина активны, при переходе во вкладку woocommerce-настройки-интеграция, ошибка - Fatal error: Cannot declare class WC_RPAEFW_Post_Calc_Method, because the name is already in use in /hosting/***/russian-post-and-ems-for-woocommerce.php on line 142

Понять не могу, ведь в вашем плагине такой класс вроде не используется, в чем может быть проблема?

**Comment by vguns** [comment]
ошибку вызывает
                 $wc_shipping = new WC_Shipping();
                 $wc_shipping_list = $wc_shipping->get_shipping_methods();

**Comment by vguns** [comment]
что если их заменить на 
$wc_shipping_list = WC()->shipping->get_shipping_methods();
будет ли работать корректно?

прошу прощения я не очень силен в php

**Comment by iyzoer** [comment]
Да, либо вместо $wc_shipping = new WC_Shipping(); получать объект ещё таким способом
$wc_shipping = WC_Shipping::instance();

**Comment by iyzoer** [comment]
Я так полагаю, что ошибка в плагине почты России. В файле russian-post-and-ems-for-woocommerce.php класс WC_RPAEFW_Post_Calc_Method не проверяется перед объявлением, как это описано в документации - https://docs.woocommerce.com/document/shipping-method-api/#section-3

**Comment by vguns** [comment]
Спасибо большое
