### ISSUE TITLE
Не обновляет заказы в woocommerce

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#30]
Все работало теперь выдает ошибку
[23-Nov-2017 11:12:00 UTC] PHP Fatal error:  Uncaught Error: Call to a member function isSuccessful() on null in */include/class-wc-retailcrm-history.php:137
Stack trace:
#0 /*/include/class-wc-retailcrm-history.php(50): WC_Retailcrm_History->ordersHistory('2017-11-22 11:1...')
#1 /*/woo-retailcrm/retailcrm.php(270): WC_Retailcrm_History->getHistory()
#2 /*/wp-includes/class-wp-hook.php(298): retailcrm_history_get()
#3 /*/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 /*/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#5 /*/wp-cron.php(117): do_action_ref_array('retailcrm_histo...', Array)
#6 {main}
  thrown in /*/include/class-wc-retailcrm-history.php on line 137

Что можно сделать чтоб заработало?

**Comment by iyzoer** [comment]
Эта ошибка систематически появляется при выгрузке истории? Проверьте настройки плагина. Похоже что при создании объекта WC_Retailcrm_Proxy передаются некорректные параметры.

**Comment by vguns** [comment]
Да плагин пытается выгрузить заказы из retailcrm, в retailcrm заказы создаются нормально

**Comment by vguns** [comment]
iyzoer, спасибо за быстрые ответы.
Представляете, я только что зарегистрировал новый аккаунт retailcrm, и в нем все работает как часы.
Получается что что то блокирует запросы на стороне retailcrm? Может подскажите что можно предпринять в этой ситуации?
