### ISSUE TITLE
Передача xmlid для Мойсклад

### ISSUE THREAD

**Issue by haidarzhy** [retailcrm/woocommerce-module#31]
Можно ли добавить передачу SKU Woocommerce как xmlid в ICML файл, чтобы корректно передавать заказы в Мойсклад из RetailCRM?

**Comment by iyzoer** [comment]
Вы можете в директории wp-content создать директорию retailcrm-custom и там разместить копию файла class-wc-retailcrm-icml.php со своими доработками.

**Comment by haidarzhy** [comment]
А почему вы не хотите добавить? Потому что это не прямой функционал Retail CRM, а свять с другими продуктами?

Я попробую сделать сам, но Pull Request можно не делать, вы все равно правку не примете?

**Comment by gwinn** [comment]
> Потому что это не прямой функционал RetailCRM, а связь с другими продуктами?

Да, именно по этой причине мы не добавляем в модули дополнительные интеграционные возможности. При связке более чем 2-х систем появляется немалое количество вариантов настройки, все учесть нельзя, и то что подойдет одним пользователям может не устроить других. 

Для подобных ситуаций мы и добавили возможность кастомизации исходного кода модуля так, как описано выше.
