### ISSUE TITLE
Incompatibility with 'High-Performance order storage (COT)'

### ISSUE THREAD

**Issue by GitVasiliy** [retailcrm/woocommerce-module#315]
This feature will soon be enabled by default in all new woocommerce installations. Are there any plans to finalize the plugin to support it?

[Upgrade recipe book](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book)

**Comment by gwinn** [comment]
No plans yet, maybe late autumn
