### ISSUE TITLE
Пропадают вариации товаров из выгрузки

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#33]
При генерации icml файла в нём периодически то у одного, то у другого вариативного товара отсутствует часть вариаций. В версии плагина до изменения кастомных классов проблема была решена сменой значения $limit = 100; на $limit = 300; Сейчас при изменении этого значения выше 150-200 кастомный клас вообще не обрабатывается и icml не генерируется.

В кастомном классе class-wc-retailcrm-icml.php у меня добавлено вот это только:

                        $weight = $product->get_weight();

                        if (!empty($weight)) {
                            $params[] = array('code' => 'weight', 'name' => 'Weight', 'value' => $weight ." кг");
                        }

                        $dimensions = $product->get_dimensions(false);
                        if (!empty($dimensions)) {
                            $arDimensions = array(
                                'length' => 'Длина',
                                'width' => 'Ширина',
                                'height' => 'Высота'
                            );
                            foreach ($dimensions as $name_dimension => $dimension) {
                                if (!empty($dimension)) {
                                    $params[] = array(
                                        'code' => $name_dimension,
                                        'name' => $arDimensions[$name_dimension],
                                        'value' => $dimension . " см"
                                    );
                                }
                            }
                        }

                        $attrName = '';

**Comment by iyzoer** [comment]
Воспроизвести данную проблему у себя не удалось.

**Comment by vasiliydementev** [comment]
Через техподдержку retailcrm решили проблему, помогло выставление $limit = 500;
Вообще очень странный баг, не могу поймать закономерность его появления. и в логах ничего к нему относящегося нет. Будем наблюдать.
