### ISSUE TITLE
Управление выгрузкой заказов из retailcrm в woocommerce

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#34]
По возможности добавьте пожалуйста настройку, что бы из crm в wc попадали не все заказы. Просто агрегатором заказов как раз crm является, включая каждый звонок, письмо и обращение в чат на сайте. А сейчас все эти пустые заказы в магазин уходят, создавая там мусор. Поэтому было бы удобно в магазине только обновлять статусы заказов сделанных непосредственно в магазине.

**Comment by iyzoer** [comment]
Имеете в виду выружать в магазин только заказы с определенным способом оформления?

**Comment by vasiliydementev** [comment]
Да

**Comment by vguns** [comment]
Тоже беспокоит эта проблема, почему выгружаются все подряд заказы?

**Comment by iyzoer** [comment]
Добавили в настройки плагина выбор способов оформления заказа, которые будут выгружаться из RetailCRM в WC
