### ISSUE TITLE
Не выгружает заказы обратно в woocommerce

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#36]
Бьюсь над проблемой, плагин не хочет выгружать заказы из retailcrm, пробую на нескольких сайтах везде в логах эта ошибка:

> 2017-12-11T18:43:42+00:00 CRITICAL Uncaught Exception: Ошибка в заказе. in ***/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:89
> Stack trace:
> #0 /***/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(147): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
> #1 /***/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order))
> #2 /***/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(166): WC_Abstract_Order->__construct('16940')
> #3 /***/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(50): WC_Retailcrm_History->ordersHistory('2017-12-10 15:4...')
> #4 /***/wp-content/plugins/woo-retailcrm/retailcrm.php(270): WC_Retailcrm_History

**Comment by iyzoer** [comment]
А заказ с идентификатором 16940 существует на сайте? Убедитесь, что нет заказов в CRM из других источников, которые по тому же API ключу приходят.

**Comment by vguns** [comment]
Заказа 16940 нет ни на сайте ни в црм.
В црм удалил все заказы и пользователей
В вукомерце тоже удалил заказы, очистил логи,очистил крон wp на всякий случай.
Посмотрел get запросом - /api/v5/orders?- точно нет заказа 16940
Сделал заказ на сайте, в црм изменил его статус и состав, на сайте изменений нет.
а в логах та же самая ошибка __construct('16940')

**Comment by vguns** [comment]
Заказа 16940 нет ни на сайте ни в црм.
Ранее по этому же api-ключу я передавал заказы с другого сайта, поэтому на этот раз, отключил все старые ключи и создал новый.
В црм удалил все заказы и пользователей
В вукомерце тоже удалил заказы, очистил логи,очистил крон wp на всякий случай.
Посмотрел get запросом - /api/v5/orders?- точно нет заказа 16940
Сделал заказ на сайте, в црм изменил его статус и состав, на сайте изменений нет.
а в логах та же самая ошибка __construct('16940')

**Comment by vguns** [comment]
Спасибо за подсказку про ключ, спустя час, заказы начали обновляться,ошибка пропала, каждый источник теперь имеет свой ключ

**Comment by gwinn** [comment]
Коллега, с вопросами по конкретному подключению пожалуйста обращайтесь в техническую поддержку RetailCRM, тут мы только технические моменты по самому плагину обсуждаем
