### ISSUE TITLE
Не все товары из магазина попадают в icml (решение)

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#39]
Добрый день! Актуально для версии WP 4.9.1 WC 3.2.6 и плагина WooCommerce RetailCRM 2.0.0

В файле class-wc-retailcrm-icml.php при значении $limit = 100; периодически не все вариации товаров попадают в xml. Лечится выставлением $limit = 500;

Если нужно и расскажете как, могу попробовать отловить ошибку.

**Comment by iyzoer** [comment]
Не уверен что это универсальное решение, скорее частный случай. Тестировали выгрузку более 1000 товарных позиций, при разных лимитах результат получали один.

**Comment by vasiliydementev** [comment]
Если возможно, просьба добавить установку значения лимита в настройки плагина, а то при обновлении каждый раз приходится руками править =)

**Comment by iyzoer** [comment]
Воспроизвести данную ошибку не удалось. Переработали механику генерации каталога, теперь для каждого товара выбираются его торговые предложения, если они есть.
