### ISSUE TITLE
Вес товаров в выгрузке icml

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#40]
Добрый день! Retailcrm по умолчанию принимает вес товаров в граммах. Если же в настройках woocommerce установлен вес по умолчанию в килограммах, то вес в crm передаётся неверный.

Хорошо бы проверять в чём измеряется вес в магазине и передавать правильные значения.

Пока что решается заменой "$params[] = array('code' => 'weight', 'name' => 'Вес', 'value' => $product->get_weight());" на "$params[] = array('code' => 'weight', 'name' => 'Вес', 'value' => $product->get_weight() ." кг");".
Тогда вес нормально учитывается и считается при доставке.

PS аналогично для размеров по идее должно работать, но поскольку сейчас модули служб доставки (сдэк по крайне мере) не считают габариты заказа, то фикс для размеров не важен.

**Comment by iyzoer** [comment]
Единицы измерения веса и размеров учтем.

**Comment by iyzoer** [comment]
Добавлена выгрузка веса и размеров с предварительной конвертацией единиц измерения.
