### ISSUE TITLE
Размеры товаров при выгрузке icml

### ISSUE THREAD

**Issue by Zek84** [retailcrm/woocommerce-module#42]
Доброй ночи! При загрузке icml не подгружаются размеры товаров, вес подгружается.  В самом icml размеры есть, а в crm не доходят. Для расчета доставки  сдэком нужны размеры. Подскажите куда копать?

**Comment by iyzoer** [comment]
Здравствуйте. По вопросам интеграции, которые не связаны с плагином, обращайтесь в техподдержку RetailCRM.
