### ISSUE TITLE
Состав заказа - Скидка

### ISSUE THREAD

**Issue by nailandroid** [retailcrm/woocommerce-module#47]
После версии 2.0.2 сломались скидки при условии что в товаре одной позиции больше чем 1 шт. Проверено на версии 2.0.3 и 2.0.4. На сайте клиент совершает покупку товара без скидки в количестве 3 шт. по 179 грн., в CRM падает товар уже со скидкой и при этом **ИТОГО** выводит правильную сумму, но **Стоимость товаров и Сумма скидок по заказу** показывает ерунду.
![skidkacrm](https://user-images.githubusercontent.com/36037978/35678634-d293994e-075c-11e8-9f3b-0b9fa095fd0c.png)

**Comment by iyzoer** [comment]
Да, была ошибка в рассчете скидки на товарную позицию, если товара в позиции больше одного. Исправили в 2.0.5

**Comment by nailandroid** [comment]
Спасибо, после обновления до версии 2.0.5 ошибка исчезла.
