### ISSUE TITLE
PHP Warning:  count()

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#49]
Обновился до php 7.2, в логах теперь ошибка:
 PHP Warning:  count(): Parameter must be an array or an object that implements Countable in */retailcrm-custom/class-wc-retailcrm-icml.php on line 312
 У меня на этой строке `if (is_null($haystack[$key]) || $haystack[$key] === '' || count($haystack[$key]) == 0) {`

**Comment by iyzoer** [comment]
Warning - это не ошибка, а предупреждение. В PHP 7.2 возникает при попытке в count передавать параметр, который нельзя посчитать[Ссылка](https://wiki.php.net/rfc/counting_non_countables)
Плагин тестировался на PHP 5.3 - 7.1. Позже мы внесем правки.

**Comment by vasiliydementev** [comment]
Отлично, а то WP обновил рекомендацию к версии php до 7.2, вот я и обновился.

**Comment by iyzoer** [comment]
Добавлена проверка данных перед передачей в функцию count().
