### ISSUE TITLE
Не пересчитывает итог

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#51]
После правки заказа в retailcrm, обновленный заказ в woocommerce имеет неправильную итоговую сумму.
В логах все ок, ошибок нет

Не пересчитывает итог, когда сумма заказа меняется в меньшую сторону.
Если в заказе меняю количество товара на большее - сумма в woocommerce корректная
Если в этом же заказе уменьшаю количество товара - сумма в wocommerce остается прежняя, итог не пересчитывается.
скриншот - http://test.samogon.market/summa.jpg

почему может не срабатывать calculate_totals();?

**Comment by iyzoer** [comment]
calculate_totals() отрабатывает, но для старого объекта заказа, данные в котором уже не актуальны. Исправили в версии 2.1.0
