### ISSUE TITLE
Логин вместо ФИО

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#53]
Если одновременно с оформлением заказа еще и зарегистрироваться, то пользователь передается в црм без ФИО только логин(вместо имени).
Вопрос это нормальное поведение плагина? так и задумывалось?

**Comment by iyzoer** [comment]
Логин вместо имени передается в том случае, если имени нет. Видимо при заказе с регистрацией при вызове нашего обработчика в базе ещё нет полной информации о пользователе.

**Comment by iyzoer** [comment]
Не работал обработчик, вызываемый при изменении клиента. Исправлено в новой версии.
