### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function set_order_id()

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#58]
В логах пхп 7.2 вылезает вот это:
`[10-Apr-2018 12:41:15 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set_order_id() on boolean in /var/www/*/html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php:367
Stack trace:
#0 /var/www/*/html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(198): WC_Retailcrm_History->orderEdit(Array, Array)
#1 /var/www/*/html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(69): WC_Retailcrm_History->ordersHistory('2018-04-09 12:3...', '2325')
#2 /var/www/*/html/wp-content/plugins/woo-retailcrm/retailcrm.php(238): WC_Retailcrm_History->getHistory()
#3 /var/www/*/html/wp-includes/class-wp-hook.php(286): retailcrm_history_get()
#4 /var/www/*/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/*/html/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#6 /var/www/*/html/wp-cron.php(126): do_action_ref_array('retailcrm_histo...', Array)
#7 {main}
  thrown in /var/www/*/html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php on line 367
`
Версия плагина 2.1.31

**Comment by vasiliydementev** [comment]
в версии 3.0.0 ошибка не появлялась, зато вылезла вот эта https://github.com/retailcrm/woocommerce-module/issues/63

**Comment by iyzoer** [comment]
Ошибку данную воспроизвести не удалось. В новых версиях плагина данный код, который вызывал ошибку был заменен.
