### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_billing_country() on null in

### ISSUE THREAD

**Issue by vasiliydementev** [retailcrm/woocommerce-module#63]
В новой версии плагина (3.0.0) появилась ошибка, вот что в логах:
[27-Apr-2018 18:40:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_billing_country() on null in /var/www/.../html/wp-content/plugins/shiptor-woo/includes/class-wc-shiptor-gateway-cod.php:31
Stack trace:
#0 /var/www/.../html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(154): WC_Gateway_COD_Card->is_available()
#1 /var/www/.../html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(494): WC_Payment_Gateways->get_available_payment_gateways()
#2 /var/www/.../html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(192): WC_Retailcrm_History->orderEdit(Array, Array)
#3 /var/www/.../html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(63): WC_Retailcrm_History->ordersHistory('2018-04-26 18:4...', '2425')
#4 /var/www/.../html/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-base.php(125): WC_Retailcrm_History->getHistory()
#5 /var/www/.../html/wp-includes/class-wp-hook.php(286): WC_Retailc in /var/www/.../html/wp-content/plugins/shiptor-woo/includes/class-wc-shiptor-gateway-cod.php on line 31

### WordPress Environment ###
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###
Server Info: nginx
PHP Version: 7.2.4-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.47.0
OpenSSL/1.0.2g

**Comment by iyzoer** [comment]
Думаю новая версия плагина здесь ни при чем, ошибка возникает в файле плагина Shiptor
`Call to a member function get_billing_country() on null in /var/www/.../html/wp-content/plugins/shiptor-woo/includes/class-wc-shiptor-gateway-cod.php:31`
