### ISSUE TITLE
Ошибка с историей заказов

### ISSUE THREAD

**Issue by vitaly-safonov** [retailcrm/woocommerce-module#69]
Каждые 5 минут в админке генерируется заказ со статусом "Ожидание оплаты", а в лог валятся ошибки.
`2018-06-30T03:13:05+00:00 CRITICAL Uncaught Error: Call to a member function set_order_id() on boolean in/shop/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php:367
Stack trace:
#0 /shop/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(198): WC_Retailcrm_History->orderEdit(Array, Array)
#1 /shop/wp-content/plugins/woo-retailcrm/include/class-wc-retailcrm-history.php(69): WC_Retailcrm_History->ordersHistory('2018-06-29 00:1...', '25017')
#2 /shop/wp-content/plugins/woo-retailcrm/retailcrm.php(271): WC_Retailcrm_History->getHistory()
#3 /shop/wp-includes/class-wp-hook.php(286): retailcrm_history_get()
#4 /shop/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /shop/wp-includes/plugin.php(515): WP_Hook->do_action(Array)`

Пробовал разные версии плагинов, не помогает.

**Comment by iyzoer** [comment]
Какая версия плагина сейчас установлена? Какие ошибки есть на последней версии?

**Comment by vitaly-safonov** [comment]
@iyzoer Версия 3.2.0, ошибки которые выше.

**Comment by iyzoer** [comment]
В версии 3.2.0 на этой строке не может возникать данная ошибка.
https://github.com/retailcrm/woocommerce-module/blob/8a28888c3a2ed26ca515f2b0183799cdbe3e3b36/src/include/class-wc-retailcrm-history.php#L367
Проверьте ещё раз, и дайте знать какие ошибки имеют место быть в последней версии плагина.

**Comment by vitaly-safonov** [comment]
Обновились до версии 3.3.0, пока ошибка пропала.
