### ISSUE TITLE
Синхронизация по артикулам

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#86]
Здравствуйте, генерация каталога и синхронизация товаров в заказе, на данный момент происходит только по id продукта, планируется ли сделать выбор между id и артикулом?

**Comment by iyzoer** [comment]
Вы имеете в виду связь по полю xmlId?

**Comment by vguns** [comment]
Да, чтобы один прайс загружать и в ретейл и в мой склад

**Comment by iyzoer** [comment]
Рассмотрим такую настройку
