### ISSUE TITLE
Вопрос по синхронизации, после редактирования заказа в црм

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#87]
Пришел заказ с сайта с товаром в количестве 2 штук, в ретейле я уменьшил количество товара на 1шт, на стороне сайта это отображается как непонятная скидка, не нормальное же поведение? или так должно быть..
[скрин](http://xn--80aaasacf1alfzxrjiy0m.xn--p1ai/1.jpg)

**Comment by iyzoer** [comment]
А изначально скидки не было никакой в заказе? Вообще скидки не передаются в сторону WC, так как там они только в разрезе купонов используются.

**Comment by vguns** [comment]
нет не было, спасибо за информацию, сейчас найду в чем причина

**Comment by vguns** [comment]
Причем тестирую на чистой установке, без внесения изменений, в любом виде плагин будет такой плохой результат, попробуйте воспроизвести проблему, меняя количество товара в црм в меньшую сторону

**Comment by iyzoer** [comment]
Да, будем искать ошибку. Какая версия WC?

**Comment by vguns** [comment]
Версия 3.5.5

**Comment by vguns** [comment]
я сдаюсь, вроде все логично меняем количество товара в заказе, меняем итоговую сумму по товару, обновляем заказ. Может это все таки частный случай... скидке этой не откуда взяться по идее

**Comment by iyzoer** [comment]
Ошибка возникает из-за того, что не устанавливается поле sub_total для товарной позиции в заказе.

**Comment by vguns** [comment]
Спасибо, но очередная проблема скопировал `class-wc-retailcrm-history.php` в `retailcrm-custom`, выгрузка изменений не происходит, логи чисты ошибок нет, как узнать  почему ничего не происходит? в фале ничего не менял, удаляю папку `retailcrm-custom` выгрузка нормально идет

**Comment by iyzoer** [comment]
Имеете в виду логи сайта или логи плагина?

**Comment by vguns** [comment]
логи сайта, логи ошибок wc, f логи плагина - все строки ok
`03-06-2019 @ 13:07:46 - [orderMethodsList]  Ok
03-06-2019 @ 13:07:46 - [deliveryTypesList]  Ok
03-06-2019 @ 13:07:46 - [paymentTypesList]  Ok
03-06-2019 @ 13:07:46 - [orderMethodsList]  Ok
03-06-2019 @ 13:07:47 - [statusesList]  Ok
03-06-2019 @ 13:07:47 - [deliveryTypesList]  Ok
03-06-2019 @ 13:07:47 - [paymentTypesList]  Ok
03-06-2019 @ 13:07:47 - [apiVersions]  Ok
03-06-2019 @ 13:07:47 - [statusesList]  Ok
03-06-2019 @ 13:07:47 - [apiVersions]  Ok
03-06-2019 @ 13:07:47 - [apiVersions]  Ok
03-06-2019 @ 13:07:47 - [apiVersions]  Ok
03-06-2019 @ 13:07:48 - [apiVersions]  Ok
03-06-2019 @ 13:07:48 - [apiVersions]  Ok
03-06-2019 @ 13:07:51 - [orderMethodsList]  Ok
03-06-2019 @ 13:07:51 - [deliveryTypesList]  Ok
03-06-2019 @ 13:07:52 - [paymentTypesList]  Ok
03-06-2019 @ 13:07:52 - [statusesList]  Ok
03-06-2019 @ 13:07:52 - [apiVersions]  Ok
03-06-2019 @ 13:07:53 - [apiVersions]  Ok
03-06-2019 @ 13:07:53 - [apiVersions]  Ok`

**Comment by iyzoer** [comment]
Так а в логах есть вызовы методов `ordersHistory` и `customersHistory`?

**Comment by vguns** [comment]
Да все верно, 
Меняю заказ в црм
запускаю 
`$WC_Retailcrm_Base= new WC_Retailcrm_Base;
$WC_Retailcrm_Base->retailcrm_history_get();`
в логах
`03-06-2019 @ 13:18:15 - [customersHistory]  Ok
03-06-2019 @ 13:18:16 - [ordersHistory]  Ok`
изменений в заказе на сайте нет.

переименовываю папку  retailcrm-custom в retailcrm-custom2
меняю заказ на стороне црм, заказ на сайте изменяется

в файл class-wc-retailcrm-history.php в папке retailcrm-custom не вносил изменений.

**Comment by vguns** [comment]
домен сайта кириллический соответственно и домашняя директория, может ли это влиять?

**Comment by iyzoer** [comment]
Думаю это не должно повлиять.

**Comment by vguns** [comment]
еще момент, с подключенной "кастомизацией" в папке retailcrm-custom, изменений на сайте нет, но новый id в поле `retailcrm_orders_history_since_id` устанавливается с каждым обращением.

**Comment by iyzoer** [comment]
Возможно дело не в кастомном классе, потому что код, судя по всему, отрабатывает.

**Comment by vguns** [comment]
судя по всему не в нем, но чем тогда можно объяснить что выгрузка с црм перестает работать после появления файла `class-wc-retailcrm-history.php` в папке `retailcrm-custom`, точнее она судя по всему происходит, но видимых изменений нет. Прошу подскажите, что может быть причиной такого поведения

**Comment by iyzoer** [comment]
Сложно сказать. Здесь нужен более детальный анализ ситуации.
