### ISSUE TITLE
Не работает кастомизация class-wc-retailcrm-history.php

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#90]
Начиная с версии 3.4.3
при копировании файла class-wc-retailcrm-history.php в папку retailcrm-custom перестает работать выгрузка заказов из црм. Более подробно в конце [обсуждения](https://github.com/retailcrm/woocommerce-module/issues/87) 

В версии 3.4.2 все работает исправно

**Comment by iyzoer** [comment]
Сейчас проверил, кастом работает. Посмотрите внимательнее, может у Вас где-то явно оригинальный файл подключается.

**Comment by vguns** [comment]
к сожалению не могу найти причину. 
Нашел несколько фильтров например 
 retailcrm_history_before_save, скажите где можно увидеть список всех подобных фильтров

**Comment by iyzoer** [comment]
Списка пока нет, думаю в скором времени здесь в Wiki добавим.
