### ISSUE TITLE
Синхронизация заказов, заказы попадают в неверный профиль клиента

### ISSUE THREAD

**Issue by vguns** [retailcrm/woocommerce-module#97]
Здравствуйте.
Раньше я всегда отключал 2 хука:

```
add_action('woocommerce_created_customer', array($this, 'create_customer'), 10, 1);
add_action('woocommerce_update_customer', array($this, 'update_customer'), 10, 1)
```

Так как не понимал особой необходимости в них, случилась проблема с выгрузкой заказов, в логе стали появляться ошибки типа:
`customersGet : Error: [HTTP-code 404] Not found`
и хуки я задействовал.

Сегодня сталкиваюсь с проблемой, заказ от зарегистрированного пользователя выгружается нормально, а последующие заказы гостей цепляются на профиль предыдущего зарегистрированного клиента.

Почему так происходит?

**Comment by iyzoer** [comment]
А гости не тот же самый email указывают?

**Comment by vguns** [comment]
Да, точно, вы правы, гостей объединяет общий емэйл, точнее его отсутствие, к сожалению для повышения конверсий это необходимость, сделать мэйл необязательным полем... но почему плагин ассоциирует отсутствие емэйла с предыдущим указанным, не ругаясь в лог на отсутствие мыла, если уж это поле в логике обязательно...

**Comment by iyzoer** [comment]
В плагине нет проверки на пустоту емейла, так как сам WC подразумевает обязательность этого поля.

**Comment by vguns** [comment]
Да наверно вы правы, в рамках стандартной конфигурации, все работает.
А по полю телефон идет синхронизация покупателей?
